### ISSUE TITLE
Fix the Hacker-news Api

### ISSUE THREAD

**Issue by Rajeshpatel07** [Rajeshpatel07/Hackernews-Scraper#1]
Issue Description:
 Unstable Response from Hacker News API Causing Application Crashes

Description:

The application is currently facing an issue with the Hacker News API, where the initial response is successful, but shortly thereafter, the API starts returning null values. This behavior is leading to unexpected crashes in the application.

Initially, the API responds successfully without any apparent issues.
![workingApi](https://github.com/Rajeshpatel07/Hackernews-Scraper/assets/145205731/e0fd04f9-422f-44cf-8e8f-810b78aabd55)

But after few seconds the API responds with Null values 
![BrakedApi](https://github.com/Rajeshpatel07/Hackernews-Scraper/assets/145205731/8a529823-ead4-41a4-b59e-86bf0696062c)

Expected Resolution:

Implementing a solution to ensure consistent and reliable responses from the API to prevent application crashes.

Hint :
use a map function when making Calls to API

**Comment by pdeep1506** [comment]
Can you describe the problem further ?
And Can you also provide the .env file for the server

**Comment by Rajeshpatel07** [comment]
> Can you describe the problem further ? And Can you also provide the .env file for the server

Thanks for Showing Interest to this project 
You can checkout readme.md file for further details

**Comment by pdeep1506** [comment]
When I tried to create account, it was going into catch block.

**Comment by Rajeshpatel07** [comment]
> When I tried to create account, it was going into catch block.

Please verify your MongoDB connection. If you are using a local MongoDB instance, it is recommended to create a new database for your project. Additionally, when Starting the server, kindly take note of two crucial messages.

1) server is running  on port 8000. 
2)  Database connected successfully.

And additionally check you node version it is highly recommended to use node>=2.9.0
If you are facing this issue again please give additional information like attaching a image etc.

Thank You.
